### ISSUE TITLE
Extension throws an exception if input data formatted as XML

### ISSUE THREAD

**Issue by VDeyneko** [magestat/magento2-log-webapi#6]
Hi,

thanks for free extension!

I just found a bug, which causes extension to crash (and thus the entire system to display an exception report) if API request is formatted as XML.

Example API request:
`curl -X POST https://{domain}/api/rest/v1/products/special-price \
        -H 'Content-Type: application/xml' \
        -H 'Accept: application/xml'
        -H 'Authorization: Bearer {token}' \
        -d '<?xml version="1.0" encoding="UTF-8"?>
<request>
<prices>
<item>
<price>30.00</price>
<store_id>1</store_id>
<sku>0000212121</sku>
<price_from>2020-06-08 15:00:00</price_from>
<price_to>2020-06-09 23:59:10</price_to>
</item>
</prices>
</request>'`

I tracked down the issue, and it seems that the problem is in `\Magestat\LogWebapi\Model\Logger::write` method. While constructing the `$data` array, it tries to format the `body` as `json` using the standard `Magento\Framework\Serialize\SerializerInterface`.

I was unable to reproduce the issue on fresh system, if the extension was turned off.

Can we improve specified method to use other serializer/formatter basing on `Content-Type` header?

**Comment by williankeller** [comment]
Hi, @VDeyneko!
We appreciate your report! Unfortunately, the extension doesn't support XML logging :(
However, we already have this feature in our backlog and you can expect to see it soon.
Feel free to help us as well. Your contribution is really appreciated.

Bests,
Keller

**Comment by VDeyneko** [comment]
Thank you for the info, @williankeller .

Do you have any deadline for this feature? For now, I'm not sure, if I will be able to start working on this feature on the next week or two.

Do You have any code or extension architecture requirements, so I won't mess up any plans for future development?

**Comment by VDeyneko** [comment]
Hi, @williankeller.

I've prepared few code changes to make the extension compatible with XML requests. However, I can not push my changes to your repo. Can you check if there is an access configured for contributors?

**Comment by williankeller** [comment]
Hi @VDeyneko, sorry for the delay to reply you back. We don't have a road map in which we release the features, however, regarding the architecture requirements we recommend to follow the [Magento Guidelines](https://devdocs.magento.com/guides/v2.3/coding-standards/bk-coding-standards.html)

To push your changes to our repo, you have to fork the repository first, push the changes to your forked repo, and then create the PR to ours.

**Comment by williankeller** [comment]
You can get more details here: https://github.com/magestat/magento2-log-webapi/blob/master/.github/CONTRIBUTING.md

**Comment by williankeller** [comment]
Hi @VDeyneko,
We've published the new version [1.2.0](https://github.com/magestat/magento2-log-webapi/releases/tag/1.2.0). Thank you so much for your support and Pull request. We appreciate you being part of the community and helping us keep the Magento extensions even better.
Please give this extension a star to help us grow in the community.
